version: '3.7'

services:
  # Backend API
  tylers-list-api:
    container_name: tylers-list-api-backend
    # image: node:10.16.0
    build: ./
    command: npm start
    working_dir: /usr/src/tylers-list-api
    environment:
      POSTGRES_URI: postgres://sally:secret@postgres:5432/tylers-list-docker
      REDIS_URI: redis://redis:6379
      JWTSIGN: JWTSIGNATURE
    links:
      - postgres
      - redis
    ports: 
      - "3000:3000"
    volumes:
      - ./:/usr/src/tylers-list-api

  # Postgres
  postgres:
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tylers-list-docker
      POSTGRES_HOST: postgres
    build: postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"